sudo: false
language: python

install:
  - pip install tox

before_script:
  - psql -U postgres -c 'CREATE DATABASE ogn_test;'
  - psql -U postgres -c 'CREATE EXTENSION postgis;'

script:
  - tox

addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6-postgis-2.4

matrix:
  include:
    - python: "3.6"
      env: TOXENV='py36'
    - python: "3.7"
      env: TOXENV='py37'
    - python: "3.7"
      env: TOXENV='flake8'

after_success:
  - tox -e codecov
