language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev

addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6-postgis-2.4

before_script:
  - flake8 tests ogn_test
  - psql -U postgres -c 'CREATE DATABASE ogn_test;'
  - psql -U postgres -c 'CREATE EXTENSION postgis;'

script:
  - nosetests --with-coverage --cover-package=app
  - pip install . --upgrade
  - python -c 'import app'

after_success:
  - coveralls
